export const siteData = {
  brand: "Rashtra Sarvopari",
  tagline: "राष्ट्र सर्वोपरि",
  defaultArea: {
    state: "Uttar Pradesh",
    district: "Mathura",
    focus: "Govardhan",
    pin: "281502",
  },
  upDistricts: [
    "Agra",
    "Aligarh",
    "Ambedkar Nagar",
    "Amethi",
    "Amroha",
    "Auraiya",
    "Ayodhya",
    "Azamgarh",
    "Baghpat",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Budaun",
    "Bulandshahr",
    "Chandauli",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Gautam Buddha Nagar",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hapur",
    "Hardoi",
    "Hathras",
    "Jalaun",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur Dehat",
    "Kanpur Nagar",
    "Kasganj",
    "Kaushambi",
    "Kushinagar",
    "Lakhimpur Kheri",
    "Lalitpur",
    "Lucknow",
    "Maharajganj",
    "Mahoba",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffarnagar",
    "Pilibhit",
    "Pratapgarh",
    "Prayagraj",
    "Raebareli",
    "Rampur",
    "Saharanpur",
    "Sambhal",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shamli",
    "Shravasti",
    "Siddharthnagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Unnao",
    "Varanasi",
  ],
  areaOptions: [
    { name: "Mathura", pin: "281001", type: "City" },
    { name: "Vrindavan", pin: "281121", type: "Town" },
    { name: "Govardhan", pin: "281502", type: "Block" },
    { name: "Chhata", pin: "281401", type: "Assembly area" },
    { name: "Mant", pin: "281202", type: "Assembly area" },
    { name: "Baldeo", pin: "281301", type: "SC reserved assembly area" },
  ],
  mathuraTehsils: ["Govardhan", "Vrindavan", "Mant", "Chhata", "Baldeo"],
  govardhanTopIssues: [
    {
      key: "parikrama-traffic",
      title: "Traffic Mismanagement during Parikrama & Festivals",
      description:
        "Crowd movement, temporary diversions, parking pressure, and festival-route control around Govardhan Parikrama.",
    },
    {
      key: "parikrama-cleanliness",
      title: "Cleanliness & Solid Waste Disposal near Parikrama Marg",
      description:
        "Waste collection, dustbins, sweep cycles, and sanitation pressure on the Parikrama route and nearby markets.",
    },
    {
      key: "stray-animals",
      title: "Stray Animal Menace (Monkeys & Cattle Management)",
      description:
        "Monkey incidents, stray cattle movement, public safety, and visitor management around local heritage spots.",
    },
    {
      key: "water-sewer",
      title: "Clean Drinking Water & Sewer Infrastructure",
      description:
        "Drinking water quality, drain overflow, sewer maintenance, and ward-level infrastructure follow-up.",
    },
  ],
  stateLeadership: {
    title: "Uttar Pradesh Civic Administration",
    summary: "State-level policy, departments, and district administration follow-up node for civic delivery.",
    points: ["State: Uttar Pradesh", "District focus: Mathura", "MVP node: Govardhan"],
  },
  govardhanAffidavit: {
    summary:
      "Meghshyam Singh represents Govardhan Assembly Constituency No. 83. Official affidavit records are linked for direct public review.",
    assets:
      "Asset and liability details should be read from the official candidate affidavit source linked below.",
    contact:
      "Public contact and grievance routing should use verified government or representative office channels for Govardhan, pin 281502.",
  },
  govardhanAssemblyHistory: [
    {
      year: "2022",
      winner: "Meghshyam Singh",
      party: "BJP",
      note: "Current Govardhan MLA. BJP changed the ticket after 2017 and Meghshyam Singh won the seat.",
    },
    {
      year: "2017",
      winner: "Karinda Singh",
      party: "BJP",
      note: "BJP won Govardhan Assembly constituency before the 2022 ticket change.",
    },
    {
      year: "2012",
      winner: "Rajkumar Rawat",
      party: "BSP",
      note: "BSP held the seat before the BJP wins of 2017 and 2022.",
    },
  ],
  areaMedia: {
    Govardhan: {
      map: {
        src: "assets/govardhan-satellite-map.png",
        alt: "Govardhan satellite map",
        imageDate: "09/05/2025",
      },
      gallery: [
        {
          src: "assets/kusum-sarovar-preview.png",
          alt: "Kusum Sarovar heritage preview",
          caption: "Kusum Sarovar",
          description: "Historic sandstone ghats and waterbody near Govardhan, used here as a visual identity anchor for the local gallery.",
          featured: true,
        },
        {
          src: "assets/govardhan-heritage.jpg",
          alt: "Govardhan heritage view",
          caption: "Govardhan Parvat",
          description: "Sacred Govardhan landscape and parikrama area, shown separately from the civic issue map.",
        },
        {
          src: "assets/mathura-temple-day.jpg",
          alt: "Temple view near Mathura district",
          caption: "Radha Kund route",
          description: "Route-side heritage visual connected with the Govardhan and Radha Kund movement corridor.",
        },
        {
          src: "assets/mathura-heritage-hero.jpg",
          alt: "Mathura heritage temple at night",
          caption: "Mansi Ganga / Danghati",
          description: "Night heritage atmosphere around the Mansi Ganga and Danghati belt for gallery preview.",
        },
      ],
    },
  },
  lokSabha: {
    name: "Mathura",
    seatNo: 17,
    currentMP: "Hema Malini",
    party: "BJP",
    term: "2024 - Present",
    note: "Third consecutive term after wins in 2014 and 2019.",
    electors: "Around 18-19 lakh voters",
    turnout2024: "62.18%",
    voterNotes: "Jat, Brahmin, and Dalit voters have a strong local impact.",
    result2024: [
      { position: "Winner", name: "Hema Malini", party: "BJP" },
      { position: "Runner-up", name: "Suresh Singh", party: "BSP" },
      { position: "Third", name: "Mukesh Dhangar", party: "INC" },
    ],
    winners: [
      { year: "2024", winner: "Hema Malini", party: "BJP", note: "Current MP." },
      {
        year: "2019",
        winner: "Hema Malini",
        party: "BJP",
        note: "Won by roughly 2.93 lakh votes against Kunwar Narendra Singh (RLD).",
      },
      {
        year: "2014",
        winner: "Hema Malini",
        party: "BJP",
        note: "Won by roughly 3.40 lakh votes against Jayant Chaudhary (RLD).",
      },
      {
        year: "2009",
        winner: "Jayant Chaudhary",
        party: "RLD",
        note: "Won when RLD and BJP had an alliance.",
      },
    ],
  },
  assemblySeats: [
    {
      seatNo: 81,
      name: "Chhata",
      mla: "Laxmi Narayan Chaudhary",
      party: "BJP",
      note: "Senior leader with a strong local hold; current UP Cabinet Sugar Mills minister.",
      detail: "He has won from this region several times and has worked with different parties in the past.",
      rating: 3.8,
    },
    {
      seatNo: 82,
      name: "Mant",
      mla: "Rajesh Chaudhary",
      party: "BJP",
      note: "A famous seat in Mathura district.",
      detail: "Pt. Shyam Sunder Sharma represented this seat eight times for around 35 years before Rajesh Chaudhary defeated him in 2022.",
      rating: 3.7,
    },
    {
      seatNo: 83,
      name: "Govardhan",
      mla: "Meghshyam Singh",
      party: "BJP",
      note: "Won the 2022 Assembly election.",
      detail: "In 2017, Karinda Singh (BJP) was MLA. In 2022, BJP changed the ticket and Meghshyam Singh won.",
      rating: 3.6,
    },
    {
      seatNo: 84,
      name: "Mathura-Vrindavan",
      mla: "Shrikant Sharma",
      party: "BJP",
      note: "Won in 2017 and 2022; former Power Minister in UP government.",
      detail: "In 2022, he received 1,58,859 votes (60.26%). Runner-up Pradeep Mathur (Congress) received 49,056 votes.",
      rating: 4.0,
    },
    {
      seatNo: 85,
      name: "Baldeo",
      mla: "Puran Prakash",
      party: "BJP",
      note: "SC reserved seat; won in 2017 and 2022.",
      detail: "He won the 2012 election on an RLD ticket, then won in 2017 and 2022 with BJP.",
      reserved: "SC Reserved",
      rating: 3.5,
    },
  ],
  localBody: {
    name: "Mathura-Vrindavan Municipal Corporation",
    mayor: "Vinod Agarwal",
    party: "BJP",
    wards: 70,
    focus: "Sanitation, local development, public works, and ward-level services.",
  },
  issueCategories: [
    "Yamuna cleanliness",
    "Monkey menace",
    "Tourism facilities",
    "Street light",
    "Road repair",
    "Water supply",
    "Sanitation",
    "Sewer",
  ],
  legalPages: {
    about: {
      title: "About Rashtra Sarvopari",
      kicker: "Non-profit civic platform",
      paragraphs: [
        "Rashtra Sarvopari is a public-interest civic dashboard created to help citizens understand their local area, representatives, public issues, and development follow-up in a simple and transparent way.",
        "The platform is currently focused on the Govardhan, Mathura MVP node. Political and public-reference information is compiled from publicly available government, election, and official/public sources wherever possible.",
        "This website is not a political party, government department, or paid campaign. It is a non-profit civic technology initiative designed and developed by Krishna Gopal Sharma for public awareness and local participation.",
      ],
    },
    terms: {
      title: "Terms & Conditions",
      kicker: "Use responsibly",
      paragraphs: [
        "By using this platform, users agree to submit only civic, factual, and community-relevant information. Do not upload abusive, misleading, illegal, or private personal data about any person.",
        "Citizen reports, votes, and uploaded photos may be moderated or removed if they are spam, defamatory, unrelated, unsafe, or not useful for public civic tracking.",
        "The platform provides informational dashboards and public reporting tools. It does not guarantee official action, government response, or legal remedy for any issue submitted by a user.",
      ],
    },
    privacy: {
      title: "Privacy Policy",
      kicker: "Minimal account data",
      paragraphs: [
        "For citizen access, the platform stores a username, password hash, optional display name, optional profile photo, votes, and submitted opinions. Passwords are not stored as plain text.",
        "Issue reports may include text and optional photo proof uploaded by the user. Users should avoid uploading private documents, personal addresses, phone numbers, or sensitive identity information.",
        "Data may be stored through Netlify Functions and Netlify Blobs for the live website. Admin moderation access is reserved for the platform owner to protect the quality and safety of the public feed.",
      ],
    },
    disclaimer: {
      title: "Disclaimer",
      kicker: "Public-source information",
      paragraphs: [
        "Rashtra Sarvopari is an independent, non-profit civic information platform. It is not an official government website and is not affiliated with any government department, election body, or political party.",
        "Representative details, election references, public records, and external links are shown for awareness. Users should verify final official information directly from government websites, Election Commission sources, affidavit portals, or official representative channels.",
        "Citizen-submitted reports and votes represent public opinion and may require verification. The platform owner may correct, update, moderate, or remove content to reduce misinformation and misuse.",
      ],
    },
  },
  issueReports: [],
  affidavitFields: ["Education", "Assets", "Land/property", "Criminal cases", "Source affidavit"],
  language: {
    en: {
      navAreaBoard: "AreaBoard",
      navReport: "Report",
      navIssues: "Issues",
      navRepresentatives: "Representatives",
      heroEyebrow: "",
      nationalTagline: "Satyamev Jayate | Dedicated to the Progress of Every District in India.",
      heroTitle: "राष्ट्र सर्वोपरि",
      heroText: "Rashtra Sarvopari",
      searchTitle: "Find your area",
      searchSubtitle: "Open the local issue board for your selected district and area.",
      selectState: "Select state",
      selectDistrict: "Select district",
      selectArea: "Select tehsil",
      state: "State",
      district: "District",
      area: "Tehsil / Sub-District",
      pin: "Pin code",
      button: "Open Area Board",
      locate: "Use my location",
      clear: "Clear",
      areaViewKicker: "Area view",
      dashboardSuffix: "Dashboard",
      heritageKicker: "Local heritage",
      photoGallerySuffix: "photo gallery",
      heritageText:
        "Famous places and local visuals stay separate from the satellite issue map, so users can explore the area without confusing photos with live civic reports.",
      dashboardKicker: "Local board",
      dashboardTitle: "Govardhan Public Representatives",
      dashboardText:
        "Issue categories, verification status, and resolution progress are the main product. Representatives stay as reference, not the whole website.",
      historyKicker: "Deep view",
      historyTitle: "Mathura Constituency Political History",
      historyText: "Clean history helps voters understand long-term patterns, not only current headlines.",
      issuesKicker: "Public voice",
      issuesTitle: "Area issues grid",
      issuesText:
        "Citizens can vote on Govardhan's critical issues and submit real local opinions with photo proof.",
      prototypeForm: "Live report terminal",
      submitIssueTitle: "Submit a local issue",
      category: "Category",
      reportArea: "Area",
      shortDescription: "Short description",
      photoProof: "Photo proof",
      submitForReview: "Submit for review",
      issuePlaceholder: "Write the issue clearly...",
      buildersKicker: "India first",
      buildersTitle: "People who helped build India",
      buildersText:
        "A respectful section for national builders, freedom fighters, reformers, scientists, and public servants.",
      footerText: "National civic issue tracking platform for Indian districts.",
      copyrightText:
        "© 2026 Rashtra Sarvopari. Designed & Developed by Krishna Gopal Sharma. All Rights Reserved.",
      mediaUpdate: "Media update",
      comingSoonTitle: "Area media unavailable for",
      comingSoonText: "This area is queued for verified civic media.",
      satelliteAttribution: "Satellite Image by Google Earth | Image Date:",
      filterNotePrefix: "Showing issues for",
      filterNoteMiddle: "pin code",
      filterNoteSuffix: "only.",
      noLocalReports: "No local reports",
      noReportsTextPrefix: "No verified issue reports are available for pin code",
      noReportsTextSuffix: "yet.",
      publicPriority: "Public priority",
      voteProofText: "People can vote, add a photo, and submit verification details.",
      lokSabhaResult: "Lok Sabha result",
      savedLocally: "Saved locally for review",
      invalidPinPrefix: "Use pin code",
      invalidPinMiddle: "for",
      reportedIssues: "Reported issues",
      reportedIssuesText: "Live Govardhan civic reports received.",
      verified: "Verified",
      verifiedText: "Issues with area, category, and photo proof.",
      resolved: "Resolved",
      resolvedText: "Closed after public or admin verification.",
      topIssue: "Top issue",
      topIssueText: "Road repair and street light reports are trending.",
      issueStatus: "Issue status",
      pending: "Pending",
      pendingText: "Reports waiting for verification.",
      departmentFollowup: "Department follow-up",
      inProgress: "In Progress",
      inProgressText: "Issue shared or action started.",
      publicClose: "Public close",
      resolvedStatus: "Resolved",
      resolvedStatusText: "Closed after proof or admin review.",
      publicRating: "Public rating",
      publicRatingText: "Citizen trust score from submitted feedback.",
      memberOfParliament: "Member of Parliament",
      mpPointOne: "Third consecutive term.",
      mpPointTwo: "Won in 2014, 2019, and 2024.",
      mpPointThree: "2024 runner-up: Suresh Singh (BSP).",
      constitution: "Constitution",
      ambedkarText: "Key architect of the Constitution of India.",
      science: "Science",
      kalamText: "Inspired generations through science, service, and education.",
      freedom: "Freedom",
      gandhiText: "Led a mass movement based on non-violence and civic courage.",
      current: "Current Politics",
      history: "Political History",
      issues: "Area Issues",
      feedback: "Public Feedback",
      status: {
        Pending: "Pending",
        "In Progress": "In Progress",
        Resolved: "Resolved",
      },
      categories: {
        "Yamuna cleanliness": "River & environmental cleanliness",
        "Monkey menace": "Animal/public safety",
        "Tourism facilities": "Public facilities",
        "Street light": "Street light",
        "Road repair": "Road repair",
        "Water supply": "Water supply",
        Sanitation: "Sanitation",
        Sewer: "Sewer",
      },
    },
    hi: {
      navAreaBoard: "क्षेत्र बोर्ड",
      navReport: "रिपोर्ट",
      navIssues: "समस्याएं",
      navRepresentatives: "जनप्रतिनिधि",
      heroEyebrow: "",
      nationalTagline: "सत्यमेव जयते | भारत के हर जिले की प्रगति को समर्पित।",
      heroTitle: "राष्ट्र सर्वोपरि",
      heroText: "Rashtra Sarvopari",
      searchTitle: "अपना क्षेत्र खोजें",
      searchSubtitle: "अपने चुने हुए जिले और क्षेत्र का स्थानीय समस्या बोर्ड खोलें।",
      selectState: "राज्य चुनें",
      selectDistrict: "जिला चुनें",
      selectArea: "तहसील चुनें",
      state: "राज्य",
      district: "जिला",
      area: "तहसील / उप-जिला",
      pin: "पिन कोड",
      button: "क्षेत्र बोर्ड खोलें",
      locate: "मेरी लोकेशन",
      clear: "साफ करें",
      areaViewKicker: "क्षेत्र दृश्य",
      dashboardSuffix: "डैशबोर्ड",
      heritageKicker: "स्थानीय विरासत",
      photoGallerySuffix: "फोटो गैलरी",
      heritageText:
        "प्रसिद्ध स्थानों और स्थानीय तस्वीरों को सैटेलाइट समस्या मैप से अलग रखा गया है, ताकि लोग क्षेत्र को साफ तरीके से समझ सकें।",
      dashboardKicker: "स्थानीय बोर्ड",
      dashboardTitle: "क्षेत्र रिपोर्ट कार्ड",
      dashboardText:
        "समस्या श्रेणियां, सत्यापन स्थिति और समाधान प्रगति इस प्लेटफॉर्म का मुख्य हिस्सा हैं। जनप्रतिनिधि केवल संदर्भ के लिए दिखते हैं।",
      historyKicker: "गहरा विवरण",
      historyTitle: "मथुरा निर्वाचन क्षेत्र का राजनीतिक इतिहास",
      historyText: "साफ इतिहास मतदाताओं को सिर्फ वर्तमान खबरों से आगे जाकर लंबे समय के पैटर्न समझने में मदद करता है।",
      issuesKicker: "जन आवाज",
      issuesTitle: "क्षेत्र समस्या ग्रिड",
      issuesText:
        "नागरिक गोवर्धन की मुख्य समस्याओं पर वोट कर सकते हैं और फोटो प्रमाण के साथ असली राय भेज सकते हैं।",
      prototypeForm: "लाइव रिपोर्ट टर्मिनल",
      submitIssueTitle: "स्थानीय समस्या जमा करें",
      category: "श्रेणी",
      reportArea: "क्षेत्र",
      shortDescription: "छोटा विवरण",
      photoProof: "फोटो प्रमाण",
      submitForReview: "समीक्षा के लिए जमा करें",
      issuePlaceholder: "समस्या साफ-साफ लिखें...",
      buildersKicker: "भारत प्रथम",
      buildersTitle: "भारत निर्माण में योगदान देने वाले लोग",
      buildersText:
        "राष्ट्रीय निर्माताओं, सुधारकों, वैज्ञानिकों और लोक सेवकों के लिए सम्मानजनक सेक्शन। फोटो और जानकारी केवल सत्यापित स्रोतों के साथ जोड़ी जानी चाहिए।",
      footerText: "भारतीय जिलों के लिए राष्ट्रीय नागरिक समस्या ट्रैकिंग प्लेटफॉर्म।",
      copyrightText:
        "© 2026 Rashtra Sarvopari. कृष्ण गोपाल शर्मा द्वारा डिजाइन और विकसित। सर्वाधिकार सुरक्षित।",
      mediaUpdate: "मीडिया अपडेट",
      comingSoonTitle: "इस क्षेत्र का मीडिया अभी उपलब्ध नहीं:",
      comingSoonText: "यह क्षेत्र सत्यापित नागरिक मीडिया के लिए कतार में है।",
      satelliteAttribution: "Google Earth द्वारा सैटेलाइट इमेज | इमेज दिनांक:",
      filterNotePrefix: "दिखाई जा रही समस्याएं",
      filterNoteMiddle: "पिन कोड",
      filterNoteSuffix: "के लिए ही हैं।",
      noLocalReports: "कोई स्थानीय रिपोर्ट नहीं",
      noReportsTextPrefix: "पिन कोड",
      noReportsTextSuffix: "के लिए अभी कोई सत्यापित समस्या रिपोर्ट उपलब्ध नहीं है।",
      publicPriority: "जन प्राथमिकता",
      voteProofText: "लोग वोट कर सकते हैं, फोटो जोड़ सकते हैं और सत्यापन विवरण जमा कर सकते हैं।",
      lokSabhaResult: "लोकसभा परिणाम",
      savedLocally: "समीक्षा के लिए लोकल सेव हुआ",
      invalidPinPrefix: "कृपया पिन कोड",
      invalidPinMiddle: "का उपयोग करें:",
      reportedIssues: "रिपोर्ट की गई समस्याएं",
      reportedIssuesText: "गोवर्धन की लाइव नागरिक रिपोर्टें।",
      verified: "सत्यापित",
      verifiedText: "क्षेत्र, श्रेणी और फोटो प्रमाण वाली समस्याएं।",
      resolved: "समाधान",
      resolvedText: "जन या एडमिन सत्यापन के बाद बंद।",
      topIssue: "मुख्य समस्या",
      topIssueText: "सड़क मरम्मत और स्ट्रीट लाइट रिपोर्ट अभी ट्रेंड कर रही हैं।",
      issueStatus: "समस्या स्थिति",
      pending: "लंबित",
      pendingText: "सत्यापन की प्रतीक्षा कर रही रिपोर्ट।",
      departmentFollowup: "विभाग फॉलो-अप",
      inProgress: "कार्य जारी",
      inProgressText: "समस्या साझा हुई या कार्रवाई शुरू हुई।",
      publicClose: "जन बंद",
      resolvedStatus: "समाधान हुआ",
      resolvedStatusText: "प्रमाण या एडमिन समीक्षा के बाद बंद।",
      publicRating: "जन रेटिंग",
      publicRatingText: "नागरिक प्रतिक्रिया से बना भरोसा स्कोर।",
      memberOfParliament: "सांसद",
      mpPointOne: "लगातार तीसरा कार्यकाल।",
      mpPointTwo: "2014, 2019 और 2024 में जीत।",
      mpPointThree: "2024 रनर-अप: सुरेश सिंह (BSP)।",
      constitution: "संविधान",
      ambedkarText: "भारत के संविधान के प्रमुख निर्माता।",
      science: "विज्ञान",
      kalamText: "विज्ञान, सेवा और शिक्षा से पीढ़ियों को प्रेरित किया।",
      freedom: "स्वतंत्रता",
      gandhiText: "अहिंसा और नागरिक साहस पर आधारित जन आंदोलन का नेतृत्व किया।",
      current: "वर्तमान राजनीति",
      history: "राजनीतिक इतिहास",
      issues: "क्षेत्र की समस्याएं",
      feedback: "जन प्रतिक्रिया",
      status: {
        Pending: "लंबित",
        "In Progress": "कार्य जारी",
        Resolved: "समाधान हुआ",
      },
      categories: {
        "Yamuna cleanliness": "नदी और पर्यावरण स्वच्छता",
        "Monkey menace": "जन/पशु सुरक्षा",
        "Tourism facilities": "सार्वजनिक सुविधाएं",
        "Street light": "स्ट्रीट लाइट",
        "Road repair": "सड़क मरम्मत",
        "Water supply": "पानी सप्लाई",
        Sanitation: "सफाई",
        Sewer: "सीवर",
      },
    },
  },
};

